### ISSUE TITLE
Creating new users doesn't work anymore

### ISSUE THREAD

**Issue by rubriks** [rubriks/r3pl4y#7]
It worked earlier. Not sure why it crashes now.

**Comment by rubriks** [comment]
Started GET "/users/auth/facebook" for 192.168.0.14 at 2015-12-05 19:07:31 +0000
Started GET "/users/auth/facebook/callback?code=AQBCQJaXTRhJ9ias7WM5ow5JlB-nj7QhVW5i9D1ee85vhQSQoC6QQw7ogeo29Pi_4ORXrIX-9E8v8q6IxRnqv6aRzhyXol9AKaSQp9nooyJrhvxGUsgcumjOnIxO_Wj-ZCwx29UT9BTWL5RyRZRnrU-VUpKpov_qVfFM-8hQkI_6Uqp4oNiSoW3bhPH0dX61tpHoVY6aEFBFnXqr0QIK1R79z5ljZLxFl9ZQuZMPX4FSMYdFezDCeuZQwBcnLaz9621oxDMvOHBa-YbfgB4-4nf0Vna3g1esW_28RXDj3_gRKw_R4iyQ-XKaE8wV7S66gSRGXuZpCtuaNzzK5j2ovVIi&state=72530d2d4fdc96981c1eb2e80e449fec664e4c77c011b345" for 192.168.0.14 at 2015-12-05 19:07:31 +0000
Processing by OmniauthCallbacksController#facebook as HTML
  Parameters: {"code"=>"AQBCQJaXTRhJ9ias7WM5ow5JlB-nj7QhVW5i9D1ee85vhQSQoC6QQw7ogeo29Pi_4ORXrIX-9E8v8q6IxRnqv6aRzhyXol9AKaSQp9nooyJrhvxGUsgcumjOnIxO_Wj-ZCwx29UT9BTWL5RyRZRnrU-VUpKpov_qVfFM-8hQkI_6Uqp4oNiSoW3bhPH0dX61tpHoVY6aEFBFnXqr0QIK1R79z5ljZLxFl9ZQuZMPX4FSMYdFezDCeuZQwBcnLaz9621oxDMvOHBa-YbfgB4-4nf0Vna3g1esW_28RXDj3_gRKw_R4iyQ-XKaE8wV7S66gSRGXuZpCtuaNzzK5j2ovVIi", "state"=>"72530d2d4fdc96981c1eb2e80e449fec664e4c77c011b345"}
Completed 500 Internal Server Error in 1034ms

ActionView::MissingTemplate (Missing template omniauth_callbacks/facebook, devise/omniauth_callbacks/facebook, devise/facebook, application/facebook with {:locale=>[:en], :formats=>[:html], :handlers=>[:erb, :builder]}. Searched in:
- "/var/www/app/views"
- "/var/lib/gems/1.9.1/gems/devise-2.2.0/app/views"
  ):
  actionpack (3.2.11) lib/action_view/path_set.rb:58:in `find'
  actionpack (3.2.11) lib/action_view/lookup_context.rb:109:in`find'
  actionpack (3.2.11) lib/action_view/renderer/abstract_renderer.rb:3:in `find_template'
  actionpack (3.2.11) lib/action_view/renderer/template_renderer.rb:34:in`determine_template'
  actionpack (3.2.11) lib/action_view/renderer/template_renderer.rb:10:in `render'
  actionpack (3.2.11) lib/action_view/renderer/renderer.rb:36:in`render_template'
  actionpack (3.2.11) lib/action_view/renderer/renderer.rb:17:in `render'
  actionpack (3.2.11) lib/abstract_controller/rendering.rb:110:in`_render_template'
  actionpack (3.2.11) lib/action_controller/metal/streaming.rb:225:in `_render_template'
  actionpack (3.2.11) lib/abstract_controller/rendering.rb:103:in`render_to_body'
  actionpack (3.2.11) lib/action_controller/metal/renderers.rb:28:in `render_to_body'
  actionpack (3.2.11) lib/action_controller/metal/compatibility.rb:50:in`render_to_body'
  actionpack (3.2.11) lib/abstract_controller/rendering.rb:88:in `render'
  actionpack (3.2.11) lib/action_controller/metal/rendering.rb:16:in`render'
  actionpack (3.2.11) lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
  activesupport (3.2.11) lib/active_support/core_ext/benchmark.rb:5:in`block in ms'
  /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
  activesupport (3.2.11) lib/active_support/core_ext/benchmark.rb:5:in`ms'
  actionpack (3.2.11) lib/action_controller/metal/instrumentation.rb:40:in `block in render'
  actionpack (3.2.11) lib/action_controller/metal/instrumentation.rb:83:in`cleanup_view_runtime'
  activerecord (3.2.11) lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
  actionpack (3.2.11) lib/action_controller/metal/instrumentation.rb:39:in`render'
  actionpack (3.2.11) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (3.2.11) lib/action_controller/metal/implicit_render.rb:5:in`send_action'
  actionpack (3.2.11) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.11) lib/action_controller/metal/rendering.rb:10:in`process_action'
  actionpack (3.2.11) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.11) lib/active_support/callbacks.rb:436:in`_run__1068445984__process_action__706387172__callbacks'
  activesupport (3.2.11) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.11) lib/active_support/callbacks.rb:385:in`_run_process_action_callbacks'
  activesupport (3.2.11) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.11) lib/abstract_controller/callbacks.rb:17:in`process_action'
  actionpack (3.2.11) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.11) lib/action_controller/metal/instrumentation.rb:30:in`block in process_action'
  activesupport (3.2.11) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.11) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  activesupport (3.2.11) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.11) lib/action_controller/metal/instrumentation.rb:29:in`process_action'
  actionpack (3.2.11) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.11) lib/active_record/railties/controller_runtime.rb:18:in`process_action'
  actionpack (3.2.11) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.11) lib/abstract_controller/rendering.rb:45:in`process'
  actionpack (3.2.11) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.11) lib/action_controller/metal/rack_delegation.rb:14:in`dispatch'
  actionpack (3.2.11) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.11) lib/action_dispatch/routing/route_set.rb:73:in`call'
  actionpack (3.2.11) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.11) lib/action_dispatch/routing/route_set.rb:36:in`call'
  actionpack (3.2.11) lib/action_dispatch/routing/mapper.rb:42:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in`block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in`call'
  actionpack (3.2.11) lib/action_dispatch/routing/route_set.rb:601:in `call'
  omniauth (1.1.0) lib/omniauth/strategy.rb:177:in`call!'
  omniauth (1.1.0) lib/omniauth/strategy.rb:157:in `call'
  omniauth (1.1.0) lib/omniauth/strategy.rb:392:in`call_app!'
  omniauth (1.1.0) lib/omniauth/strategy.rb:354:in `callback_phase'
  omniauth-oauth2 (1.1.0) lib/omniauth/strategies/oauth2.rb:78:in`callback_phase'
  omniauth (1.1.0) lib/omniauth/strategy.rb:219:in `callback_call'
  omniauth (1.1.0) lib/omniauth/strategy.rb:175:in`call!'
  omniauth (1.1.0) lib/omniauth/strategy.rb:157:in `call'
  omniauth (1.1.0) lib/omniauth/strategy.rb:177:in`call!'
  omniauth (1.1.0) lib/omniauth/strategy.rb:157:in `call'
  warden (1.2.1) lib/warden/manager.rb:35:in`block in call'
  warden (1.2.1) lib/warden/manager.rb:34:in `catch'
  warden (1.2.1) lib/warden/manager.rb:34:in`call'
  actionpack (3.2.11) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.3) lib/rack/etag.rb:23:in`call'
  rack (1.4.3) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/head.rb:14:in`call'
  actionpack (3.2.11) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/flash.rb:242:in`call'
  rack (1.4.3) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.3) lib/rack/session/abstract/id.rb:205:in`call'
  actionpack (3.2.11) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.11) lib/active_record/query_cache.rb:64:in`call'
  activerecord (3.2.11) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/callbacks.rb:28:in`block in call'
  activesupport (3.2.11) lib/active_support/callbacks.rb:405:in `_run__110972040__call__111268607__callbacks'
  activesupport (3.2.11) lib/active_support/callbacks.rb:405:in`__run_callback'
  activesupport (3.2.11) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.11) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (3.2.11) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/remote_ip.rb:31:in`call'
  actionpack (3.2.11) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
  railties (3.2.11) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.11) lib/rails/rack/logger.rb:16:in`block in call'
  activesupport (3.2.11) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.11) lib/rails/rack/logger.rb:16:in`call'
  actionpack (3.2.11) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.3) lib/rack/methodoverride.rb:21:in`call'
  rack (1.4.3) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.11) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  rack (1.4.3) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/static.rb:62:in`call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in`fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in`call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.11) lib/rails/engine.rb:479:in`call'
  railties (3.2.11) lib/rails/application.rb:223:in `call'
  rack (1.4.3) lib/rack/content_length.rb:14:in`call'
  railties (3.2.11) lib/rails/rack/log_tailer.rb:17:in `call'
  rack (1.4.3) lib/rack/handler/webrick.rb:59:in`service'
  /usr/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
  /usr/lib/ruby/1.9.1/webrick/httpserver.rb:94:in`run'
  /usr/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'

**Comment by rubriks** [comment]
Login to existing facebook connection works. Problem might be connected to new users.

**Comment by rubriks** [comment]
Same error creating new user from Twitter account.

Started GET "/users/auth/twitter" for 192.168.0.14 at 2015-12-05 19:38:50 +0000
Started GET "/users/auth/twitter/callback?oauth_token=5BJhlgAAAAAAGDtTAAABUXOnbHc&oauth_verifier=uNBfsGYp4fV7T6LjvMEscQHbyG0LVO1X" for 192.168.0.14 at 2015-12-05 19:38:52 +0000
Processing by OmniauthCallbacksController#twitter as HTML
  Parameters: {"oauth_token"=>"5BJhlgAAAAAAGDtTAAABUXOnbHc", "oauth_verifier"=>"uNBfsGYp4fV7T6LjvMEscQHbyG0LVO1X"}
Completed 500 Internal Server Error in 1717ms

ActionView::MissingTemplate (Missing template omniauth_callbacks/twitter, devise/omniauth_callbacks/twitter, devise/twitter, application/twitter with {:locale=>[:en], :formats=>[:html], :handlers=>[:erb, :builder]}. Searched in:
- "/var/www/app/views"
- "/var/lib/gems/1.9.1/gems/devise-2.2.0/app/views"
  ):
  actionpack (3.2.11) lib/action_view/path_set.rb:58:in `find'
  actionpack (3.2.11) lib/action_view/lookup_context.rb:109:in`find'
  actionpack (3.2.11) lib/action_view/renderer/abstract_renderer.rb:3:in `find_template'
  actionpack (3.2.11) lib/action_view/renderer/template_renderer.rb:34:in`determine_template'
  actionpack (3.2.11) lib/action_view/renderer/template_renderer.rb:10:in `render'
  actionpack (3.2.11) lib/action_view/renderer/renderer.rb:36:in`render_template'
  actionpack (3.2.11) lib/action_view/renderer/renderer.rb:17:in `render'
  actionpack (3.2.11) lib/abstract_controller/rendering.rb:110:in`_render_template'
  actionpack (3.2.11) lib/action_controller/metal/streaming.rb:225:in `_render_template'
  actionpack (3.2.11) lib/abstract_controller/rendering.rb:103:in`render_to_body'
  actionpack (3.2.11) lib/action_controller/metal/renderers.rb:28:in `render_to_body'
  actionpack (3.2.11) lib/action_controller/metal/compatibility.rb:50:in`render_to_body'
  actionpack (3.2.11) lib/abstract_controller/rendering.rb:88:in `render'
  actionpack (3.2.11) lib/action_controller/metal/rendering.rb:16:in`render'
  actionpack (3.2.11) lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
  activesupport (3.2.11) lib/active_support/core_ext/benchmark.rb:5:in`block in ms'
  /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
  activesupport (3.2.11) lib/active_support/core_ext/benchmark.rb:5:in`ms'
  actionpack (3.2.11) lib/action_controller/metal/instrumentation.rb:40:in `block in render'
  actionpack (3.2.11) lib/action_controller/metal/instrumentation.rb:83:in`cleanup_view_runtime'
  activerecord (3.2.11) lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
  actionpack (3.2.11) lib/action_controller/metal/instrumentation.rb:39:in`render'
  actionpack (3.2.11) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (3.2.11) lib/action_controller/metal/implicit_render.rb:5:in`send_action'
  actionpack (3.2.11) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.11) lib/action_controller/metal/rendering.rb:10:in`process_action'
  actionpack (3.2.11) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.11) lib/active_support/callbacks.rb:436:in`_run__1068445984__process_action__687228460__callbacks'
  activesupport (3.2.11) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.11) lib/active_support/callbacks.rb:385:in`_run_process_action_callbacks'
  activesupport (3.2.11) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.11) lib/abstract_controller/callbacks.rb:17:in`process_action'
  actionpack (3.2.11) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.11) lib/action_controller/metal/instrumentation.rb:30:in`block in process_action'
  activesupport (3.2.11) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.11) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  activesupport (3.2.11) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.11) lib/action_controller/metal/instrumentation.rb:29:in`process_action'
  actionpack (3.2.11) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.11) lib/active_record/railties/controller_runtime.rb:18:in`process_action'
  actionpack (3.2.11) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.11) lib/abstract_controller/rendering.rb:45:in`process'
  actionpack (3.2.11) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.11) lib/action_controller/metal/rack_delegation.rb:14:in`dispatch'
  actionpack (3.2.11) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.11) lib/action_dispatch/routing/route_set.rb:73:in`call'
  actionpack (3.2.11) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.11) lib/action_dispatch/routing/route_set.rb:36:in`call'
  actionpack (3.2.11) lib/action_dispatch/routing/mapper.rb:42:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in`block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in`call'
  actionpack (3.2.11) lib/action_dispatch/routing/route_set.rb:601:in `call'
  omniauth (1.1.0) lib/omniauth/strategy.rb:177:in`call!'
  omniauth (1.1.0) lib/omniauth/strategy.rb:157:in `call'
  omniauth (1.1.0) lib/omniauth/strategy.rb:177:in`call!'
  omniauth (1.1.0) lib/omniauth/strategy.rb:157:in `call'
  omniauth (1.1.0) lib/omniauth/strategy.rb:392:in`call_app!'
  omniauth (1.1.0) lib/omniauth/strategy.rb:354:in `callback_phase'
  omniauth-oauth (1.0.1) lib/omniauth/strategies/oauth.rb:58:in`callback_phase'
  omniauth (1.1.0) lib/omniauth/strategy.rb:219:in `callback_call'
  omniauth (1.1.0) lib/omniauth/strategy.rb:175:in`call!'
  omniauth (1.1.0) lib/omniauth/strategy.rb:157:in `call'
  warden (1.2.1) lib/warden/manager.rb:35:in`block in call'
  warden (1.2.1) lib/warden/manager.rb:34:in `catch'
  warden (1.2.1) lib/warden/manager.rb:34:in`call'
  actionpack (3.2.11) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.3) lib/rack/etag.rb:23:in`call'
  rack (1.4.3) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/head.rb:14:in`call'
  actionpack (3.2.11) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/flash.rb:242:in`call'
  rack (1.4.3) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.3) lib/rack/session/abstract/id.rb:205:in`call'
  actionpack (3.2.11) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.11) lib/active_record/query_cache.rb:64:in`call'
  activerecord (3.2.11) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/callbacks.rb:28:in`block in call'
  activesupport (3.2.11) lib/active_support/callbacks.rb:405:in `_run__110972040__call__111268607__callbacks'
  activesupport (3.2.11) lib/active_support/callbacks.rb:405:in`__run_callback'
  activesupport (3.2.11) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.11) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (3.2.11) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/remote_ip.rb:31:in`call'
  actionpack (3.2.11) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
  railties (3.2.11) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.11) lib/rails/rack/logger.rb:16:in`block in call'
  activesupport (3.2.11) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.11) lib/rails/rack/logger.rb:16:in`call'
  actionpack (3.2.11) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.3) lib/rack/methodoverride.rb:21:in`call'
  rack (1.4.3) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.11) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  rack (1.4.3) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/static.rb:62:in`call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in`fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in`call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.11) lib/rails/engine.rb:479:in`call'
  railties (3.2.11) lib/rails/application.rb:223:in `call'
  rack (1.4.3) lib/rack/content_length.rb:14:in`call'
  railties (3.2.11) lib/rails/rack/log_tailer.rb:17:in `call'
  rack (1.4.3) lib/rack/handler/webrick.rb:59:in`service'
  /usr/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
  /usr/lib/ruby/1.9.1/webrick/httpserver.rb:94:in`run'
  /usr/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
